#ifndef ARM_CONFIG_H
#define ARM_CONFIGL_H

#define EXP_ENVI_STATUS_MSG_LEN			1
#define EXP_ENVI_STATUS_MSG_START_IDX	1
#define EXP_ENVI_CMD_MSG_LEN				1
#define EXP_ENVI_CMD_MSG_START_IDX		1

#define ROBOT_POSITION_MSG_LEN		2*THREE_DOF_ROBOT_NUM_OF_SERVOS
#define ROBOT_POSITION_MSG_START_IDX	EXP_ENVI_STATUS_MSG_START_IDX+EXP_ENVI_STATUS_MSG_LEN

#define ROBOT_PW_CMD_MSG_LEN		2*THREE_DOF_ROBOT_NUM_OF_SERVOS
#define ROBOT_PW_CMD_MSG_START_IDX	EXP_ENVI_CMD_MSG_START_IDX+EXP_ENVI_CMD_MSG_LEN

#define RX_BUFF_SIZE				1 + EXP_ENVI_STATUS_MSG_LEN + (2*THREE_DOF_ROBOT_NUM_OF_SERVOS) + 2		// 0xFF + EXP_ENVI_STATUS (1 BYTE) + SERVO_0_POSITION_L_BYTE + SERVO_0_POSITION_H_BYTE + SERVO_1_POSITION_L_BYTE + SERVO_1_ POSITION_H_BYTE + SERVO_2_POSITION_L_BYTE + SERVO_2_ POSITION_H_BYTE + 0xFF + 0xFF

#define PW_TX_BUFF_SIZE			1 + EXP_ENVI_CMD_MSG_LEN + (2*THREE_DOF_ROBOT_NUM_OF_SERVOS) + 2		// 'P' + EXP_ENVI_COMND (1 BYTE) + SERVO_0_PW_L_BYTE + SERVO_0_PW_H_BYTE + SERVO_1_PW_L_BYTE + SERVO_1_ PW_H_BYTE + SERVO_2_PW_L_BYTE + SERVO_2_ PW_H_BYTE + 0xFF + 0xFF	

#define ADC_TX_BUFF_SIZE			1 + EXP_ENVI_CMD_MSG_LEN + 2		// 'A' + EXP_ENVI_COMND (1 BYTE) + 0xFF + 0xFF	





#define BASE_SERVO_0_DEGREE_PULSE		2090
#define BASE_SERVO_90_DEGREE_PULSE		1544
#define BASE_SERVO_0_DEGREE_ADC_VAL		60
#define BASE_SERVO_90_DEGREE_ADC_VAL	465

#define SHOULDER_SERVO_0_DEGREE_PULSE		958
#define SHOULDER_SERVO_90_DEGREE_PULSE		1434
#define SHOULDER_SERVO_0_DEGREE_ADC_VAL	222
#define SHOULDER_SERVO_90_DEGREE_ADC_VAL	349

#define ELBOW_SERVO_0_DEGREE_PULSE		914
#define ELBOW_SERVO_90_DEGREE_PULSE		1394
#define ELBOW_SERVO_0_DEGREE_ADC_VAL	227
#define ELBOW_SERVO_90_DEGREE_ADC_VAL	353

#define BASE_SERVO_INIT_PULSE				BASE_SERVO_90_DEGREE_PULSE   
#define SHOULDER_SERVO_INIT_PULSE		1531
#define ELBOW_SERVO_INIT_PULSE			1444




#include "Gui.h"
#include "ArmConfigRtTask.h"




#endif
