


/// INPUTS
#define IR_BEAM_IDX_IN_EXP_ENVI_DATA		0
#define LEFT_LEVER_IDX_IN_EXP_ENVI_DATA	1
#define RIGHT_LEVER_IDX_IN_EXP_ENVI_DATA	2


/// OUTPUTS
#define VALVE_IDX_IN_EXP_ENVI_DATA				0
#define BUZZER_IDX_IN_EXP_ENVI_DATA			1
#define LEFT_LED_IDX_IN_EXP_ENVI_DATA			2
#define RIGHT_LED_IDX_IN_EXP_ENVI_DATA		3
#define GUIDE_LED_IDX_IN_EXP_ENVI_DATA		4
#define LEVER_SOLENOID_IDX_IN_EXP_ENVI_DATA	5

